### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by alexandre-mbm** [albfan/git-graph#4]
I want to work with you (see alexandre-mbm/gitgraph#1). But my code uses a four-spaces pattern while the your uses a three-spaces pattern. Would you accept a prior pull request for making your code with a four-spaces pattern? This greatly facilitate the work of merging and is a more common pattern.

**Comment by alexandre-mbm** [comment]
Forget it. Now I see 928da9285a2572bbbe5cf33a725ed7be7c8455cb. I will look other merge strategy.

**Comment by albfan** [comment]
If this introduce noise in history we can rebase and edit history to expose a coherent succesion of changes.

**Comment by alexandre-mbm** [comment]
I think that firstly you can try accept the pull requests #6 and #3. If you do rebase to a 4-spaces pattern, I think that can help. But I suggest that you try do these pull requests before.

**Comment by albfan** [comment]
I prefer 3 spaces. Maybe change to 2 spaces would be even better

**Comment by alexandre-mbm** [comment]
Thank you for the clarification. :+1:
