### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by alexandre-mbm** [albfan/git-graph#5]
```console
$ ./git-graph -a
Entrada em falta: -
$ git branch
* github-albfan
  googlecode-fixkowalski
  googlecode-gitgraph
  master
  master-3spaces
$ git graph
git: 'graph' não é um comando git. Veja 'git --help'.

Você quis dizer estas coisas?
	branch
	grep
```

**Comment by albfan** [comment]
Please give a concise description on title and an english detailed explanation of the problem. i guess this is related to installation. If you put git-graph on PATH, git assume it as a new command.

**Comment by alexandre-mbm** [comment]
```console
$ export PATH="$PATH:$(pwd)"; echo $PATH
[my note: here was OK]
$ git graph
Entrada em falta: -
$
```
I don't speak English. My system is in pt-BR.

**Comment by albfan** [comment]
To debug, run it with:

    $ git_graph_DEBUG=1 git graph

and post output here
